### ISSUE TITLE
Silent Renew Question

### ISSUE THREAD

**Issue by plambhsa** [RezareSystems/angular-identity-server-examples#1]
I see that you put the silent_renew.html file in the src folder. How do you ensure that the silent_renew.html file is loaded by the application?

I've placed my silent-renew.html file in the src folder and in the assets folder, and neither worked. When in the src folder I get an error about no matching routes, and when in the assets folder nothing happens at all.

I've confirmed that silent renew is enabled, with callback URLs enabled as well on the authorization server, but after the error pops up in the console, I only have until the access token has expired before I have to log in again.

You can see a SO question I posted about this here: https://stackoverflow.com/questions/54242756/angular-oidc-implicit-flow-silent-renew

Any help would be greatly appreciated!

**Comment by gerardl123** [comment]
On the project I had the silent_renew.html under the src folder so I had to specifically put in my angular.json under the assets array on the build section "src/silent_renew.html" this tells the angular cli to include the file in the build.

Although you did mention that you put silent_renew.html under assets which should mean it should have been included because under that same assets array on angular.json angular (by default) puts in "src/assets" which means include all files under that folder.

So I guess what you can try is try just building the app locally using ng build --prod and see whether the silent_renew.html is on the dist folder along with the other build artifacts.

What version of the angular-auth-oidc-client are you using?

What happens if you turn on debugging logs on the client. So I think you can do this if you set
log_console_debug_active and log_console_warning_active both to true on the oidc config when you set it all up on the appmodule. It provides quite an extensive log of whats happening under the hood.

Also can you also provide the redirectUrls you have set up on identity server?

**Comment by plambhsa** [comment]
So I added the "src/silent-renew.html" to the assets array, and running the ng build command I can confirm that the file is in the output folders. 

The console output looks promising. It logs the iframe for silent renew, it saws that silent-renew is running and active, etc. Here's a couple pictures:

![auth-logs](https://user-images.githubusercontent.com/14982471/51352451-e1e13880-1a6a-11e9-9b98-9b25f013d1ed.png)
![auth-logs-2](https://user-images.githubusercontent.com/14982471/51352453-e1e13880-1a6a-11e9-9ca9-aa5800d3eb49.png)

Then, after a couple minutes (I have the access token lifetime set to 2 minutes) a couple errors start to pop up:

![auth-logs-3](https://user-images.githubusercontent.com/14982471/51352635-721f7d80-1a6b-11e9-986c-1330a13f9d82.png)

The callback URLs from the auth server are:

![callbacks](https://user-images.githubusercontent.com/14982471/51352745-c1fe4480-1a6b-11e9-918b-1ce3a797eda3.png)

**Comment by gerardl123** [comment]
On this screenshot, it seems to suggest that the silent renew is working and refreshing the token because its detecting the expiration of the token then it refreshes it.
![image](https://user-images.githubusercontent.com/4155763/51354633-14e20580-1b19-11e9-8534-0fb39aa00c66.png)

On the last screenshot where the errors occur, I notice there is a line that says onUserDataChanged: Logout detected. Perhaps the user is being logged out and thus you lose the token.

Another suggestion is to actually make the silentrenewiframe visible if you make it display: block instead of display: none on the developer console just to see whats happening there.  Cause for some reason it might be that those routing errors is the silentrenewiframe doing it not your actual app. Ideally it should just be an empty page which contains the javascript that handles the callback from the server with the new token and stuff and then. Do you use the script that the angular-auth-oidc-client suggests for the silent_renew.html.

`<script>
    window.onload = function () {
    /* The parent window hosts the Angular application */
    var parent = window.parent;
    /* Send the id_token information to the oidc message handler */
    var event = new CustomEvent('oidc-silent-renew-message', {detail: window.location.hash.substr(1) });
    parent.dispatchEvent(event);
};
</script>`

**Comment by plambhsa** [comment]
I will try and figure out what would have caused the logout. I'm not sure where that would come from, as I didn't click a logout button or anything.

I'll also try making the iframe visible, in case that leads to anything.

And yes, I'm using the script for the silent-renew right from the package, copied and pasted exactly as it shows up there.

**Comment by plambhsa** [comment]
So, I've narrowed it down to what I _think_ happens. I think what happens is that every now and then, a request is made right before the refresh is done, or the refresh is done but the old access token is sent to the server, or something along those lines. The server checks the token and says that it's expired, so an error is returned to the Angular application, which then tells the Angular application to go authenticate again. And for some reason the "cannot match routes" error pops up. But like I said this doesn't happen every time.

I think I've gotten it working at this point. Thanks a ton for your help!

**Comment by gerardl123** [comment]
Glad I could help
